title: Thordog

url: http://www.thordog.com

permalink: /:year/:month/:day/:title/

name: Thordog
description: Personal blog of Chris Dellinger
url: http://www.thordog.com

author:
    name: Chris Dellinger
    github: cdellinger

comments:
    provider: disqus
    disqus:
        short_name: thordog
        
analytics:
    provider: google 
    google: 
        tracking_id: 'UA-790004-9'
        domain: 'thordog.com'